# Generated by Django 3.1.7 on 2021-03-31 16:25

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
                ('is_notify_screen', models.BooleanField(default=True)),
                ('is_push', models.BooleanField(default=True)),
                ('client_action', models.CharField(choices=[('OPEN_ARTICLE', 'Open article page'), ('OPEN_MESSAGE', 'Open message page'), ('OPEN_GIFTS', 'Open gifts page'), ('None', 'Nothing to do')], default='None', max_length=250)),
                ('icon', models.CharField(blank=True, choices=[('info.png', 'info.png'), ('mail.png', 'mail.png'), ('gift.png', 'gift.png')], default='info.png', max_length=250)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
